AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0dc9a8d2479a3c7d7
      InstanceType: !Ref InstanceTypeParameter
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter instance type. Default is t2.micro